apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n1jn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-n1jn@sha256:02f9076fd1a2933709beae5c2d9200b7c10a2798e52239b9a6c1bb91e99f4f7d
        name: my-nodejs
        resources: {}
status: {}
